---
cancel: CANCEL
instructions: 
  1: "Upload an image of your ingredients (We won’t tell if you leave out your secret ingredient!)"
  2: "Upload an image of your freshly made dish (That smells scrumptious!)"
  3: "Upload an image of how you enjoyed your dish. With friends? With family? Or with your favorite bottle of Beringer Main &amp; Vine!"
