---
copy1: "Upload an image of your ingredients (We won’t tell if you leave out your secret ingredient!)"
copy2: "Upload an image of your freshly made dish (That smells scrumptious!)"
copy3: "Upload an image of your plated or decorated dish (Or the empty plate, because we’ve all nibbled straight off the cooling rack!)"
