---
intro:
  - Prepare & Share is an easy-to-use tool designed to help you create beautiful, custom recipe pictures for your favorite dishes. In 3 simple steps, send your signature recipe photos to friends and family, collect them for your personal cookbook, or share with your followers on social media. So what are you waiting for? Let’s get cooking!
cta: get started
copyright: '&copy; 2017 MAIN & VINE. | <a href="/tandc" target="_blank">Terms &amp; Conditions</a>'
