---

white1: "#ffffff"
grey1: "#DEDEDE"
black1: "#000000"
black2: "#241F20"
beige1: "#FAF9Ed"
beige2: "#FAF9Ed"
gold1: "#8d734a"
brown1: "#93734C"
brown2: "#8E744B"
orange1: "#E8696C"
red1: "#C8004F"
cyan1: "#269A76"


facebook_blue: "#4867AA"
instagram_or: "#FF7804"
twitter_blue: "#00ACED"
