---
c1:
  font-family: Montserrat
  font-size: 16px
  font-weight: '400'
c2:
  font-family: Montserrat
  font-size: 20px
  font-weight: '400'

c3:
  font-family: Montserrat
  font-size: 12px
  font-weight: '400'

c4:
  font-family: Montserrat
  font-size: 11px
  font-weight: '400'

h1:
  font-family: Montserrat
  font-size: 30px
  font-weight: '400'
