---
c1:
  font-family: Montserrat
  font-size: 12px
  font-weight: '400'
c2:
  font-family: Montserrat
  font-size: 18px
  font-weight: '400'

c3:
  font-family: Montserrat
  font-size: 10px
  font-weight: '400'

c4:
  font-family: Montserrat
  font-size: 10px
  font-weight: '400'

h1:
  font-family: Montserrat
  font-size: 24px
  font-weight: '400'
