---
title: "Excited to share my latest recipe: {{title}}"
description: "Showcase your recipes in a snap with Prepare & Share, by Beringer Main & Vine"
twitter_description: "Excited to share my latest recipe! Publish your own with Prepare %26 Share by Beringer Main %26 Vine: "
hashtag: BetterTogether
pinterest_description: "My latest kitchen creation: {{title}}, designed for Pinterest with Prepare %26 Share by Beringer Main & Vine. Share and send your own recipes at"
